# FROM node:22-alpine AS installer

# WORKDIR /usr/src/app
# RUN corepack enable pnpm
# COPY package.json pnpm-lock.yaml ./
# RUN pnpm install --frozen-lockfile --ignore-scripts
# COPY . .
# RUN pnpm postinstall


# FROM node:22-alpine AS dev

# WORKDIR /usr/src/app
# RUN corepack enable pnpm
# COPY --from=installer /usr/src/app/ ./
# CMD [ "pnpm", "dev" ]


FROM node:22-alpine AS installer

# Install OpenSSL in the installer stage
RUN apk add --no-cache openssl

WORKDIR /usr/src/app
RUN corepack enable pnpm
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --ignore-scripts
COPY . .
RUN pnpm postinstall

FROM node:22-alpine AS dev

# Install OpenSSL in the final stage too (required for runtime)
RUN apk add --no-cache openssl

WORKDIR /usr/src/app
RUN corepack enable pnpm
COPY --from=installer /usr/src/app/ ./
CMD [ "pnpm", "dev" ]